/**
 * Seed de démonstration — Le Jardin de Bloom.
 *
 * Toutes les données créées ici sont clairement identifiables comme des
 * données de démo : compte "demo@jardindebloom.app", plantes préfixées
 * "Mon"/"Ma", et le flag `isDemo` implicite via cet unique compte connu.
 * Aucune donnée réelle d'utilisateur n'est mélangée à ce jeu de données.
 */
import { PrismaClient, PlantCategory, CareActionType, ReminderType } from "@prisma/client";
import bcrypt from "bcryptjs";

const prisma = new PrismaClient();

const ACHIEVEMENTS: Array<{
  id: string;
  family: string;
  name: string;
  description: string;
  icon: string;
  sortOrder: number;
}> = [
  // Premiers pas
  { id: "first_plant", family: "premiers_pas", name: "Première plante", description: "Tu as ajouté ta toute première plante.", icon: "🌱", sortOrder: 1 },
  { id: "first_scan", family: "premiers_pas", name: "Premier scan", description: "Tu as utilisé le scanner pour la première fois.", icon: "📷", sortOrder: 2 },
  { id: "first_analysis", family: "premiers_pas", name: "Première analyse", description: "Bloom a observé une première photo pour toi.", icon: "🔍", sortOrder: 3 },
  { id: "first_care", family: "premiers_pas", name: "Premier soin", description: "Tu as enregistré ta première action de soin.", icon: "💧", sortOrder: 4 },
  { id: "first_bloom_meeting", family: "premiers_pas", name: "Première rencontre avec Bloom", description: "Bloom t'a dit bonjour pour la première fois.", icon: "🐰", sortOrder: 5 },
  { id: "first_garden", family: "premiers_pas", name: "Premier jardin", description: "Ton jardin virtuel a pris racine.", icon: "🌳", sortOrder: 6 },
  // Collection
  { id: "collection_3", family: "collection", name: "3 plantes", description: "Ta collection compte 3 plantes.", icon: "🪴", sortOrder: 7 },
  { id: "collection_5", family: "collection", name: "5 plantes", description: "Ta collection compte 5 plantes.", icon: "🪴", sortOrder: 8 },
  { id: "collection_10", family: "collection", name: "10 plantes", description: "Ta collection compte 10 plantes.", icon: "🪴", sortOrder: 9 },
  { id: "collection_25", family: "collection", name: "25 plantes", description: "Ta collection compte 25 plantes.", icon: "🪴", sortOrder: 10 },
  { id: "collection_50", family: "collection", name: "50 plantes", description: "Ta collection compte 50 plantes.", icon: "🪴", sortOrder: 11 },
  { id: "collection_100", family: "collection", name: "100 plantes", description: "Ta collection compte 100 plantes.", icon: "🪴", sortOrder: 12 },
  // Entretien
  { id: "care_10", family: "entretien", name: "10 soins", description: "10 actions de soin enregistrées.", icon: "🧤", sortOrder: 13 },
  { id: "care_25", family: "entretien", name: "25 soins", description: "25 actions de soin enregistrées.", icon: "🧤", sortOrder: 14 },
  { id: "care_50", family: "entretien", name: "50 soins", description: "50 actions de soin enregistrées.", icon: "🧤", sortOrder: 15 },
  { id: "care_100", family: "entretien", name: "100 soins", description: "100 actions de soin enregistrées.", icon: "🧤", sortOrder: 16 },
  { id: "care_250", family: "entretien", name: "250 soins", description: "250 actions de soin enregistrées.", icon: "🧤", sortOrder: 17 },
  { id: "care_500", family: "entretien", name: "500 soins", description: "500 actions de soin enregistrées.", icon: "💚", sortOrder: 18 },
  // Régularité (cumulatif, jamais punitif)
  { id: "tracking_7", family: "regularite", name: "7 jours de suivi", description: "7 jours cumulés à prendre des nouvelles de tes plantes.", icon: "📅", sortOrder: 19 },
  { id: "tracking_14", family: "regularite", name: "14 jours de suivi", description: "14 jours cumulés de suivi.", icon: "📅", sortOrder: 20 },
  { id: "tracking_30", family: "regularite", name: "30 jours de suivi", description: "30 jours cumulés de suivi.", icon: "📅", sortOrder: 21 },
  { id: "tracking_60", family: "regularite", name: "60 jours de suivi", description: "60 jours cumulés de suivi.", icon: "📅", sortOrder: 22 },
  { id: "tracking_100", family: "regularite", name: "100 jours de suivi", description: "100 jours cumulés de suivi.", icon: "📅", sortOrder: 23 },
  { id: "tracking_365", family: "regularite", name: "365 jours de suivi", description: "Une année de suivi cumulé.", icon: "⭐", sortOrder: 24 },
  // Observation
  { id: "photos_5", family: "observation", name: "5 photos", description: "5 photos ajoutées à tes plantes.", icon: "📸", sortOrder: 25 },
  { id: "photos_10", family: "observation", name: "10 photos", description: "10 photos ajoutées.", icon: "📸", sortOrder: 26 },
  { id: "photos_25", family: "observation", name: "25 photos", description: "25 photos ajoutées.", icon: "🖼️", sortOrder: 27 },
  { id: "photos_50", family: "observation", name: "50 photos", description: "50 photos ajoutées.", icon: "🖼️", sortOrder: 28 },
  { id: "photos_100", family: "observation", name: "100 photos", description: "100 photos ajoutées.", icon: "🖼️", sortOrder: 29 },
  // Santé
  { id: "first_plant_saved", family: "sante", name: "Première plante sauvée", description: "Une plante à surveiller est redevenue en bonne forme.", icon: "💚", sortOrder: 30 },
  { id: "first_improvement", family: "sante", name: "Première amélioration", description: "Le score de santé d'une plante s'est amélioré.", icon: "📈", sortOrder: 31 },
  { id: "improvements_5", family: "sante", name: "5 améliorations", description: "5 améliorations de santé constatées.", icon: "📈", sortOrder: 32 },
  { id: "improvements_10", family: "sante", name: "10 améliorations", description: "10 améliorations de santé constatées.", icon: "📈", sortOrder: 33 },
  { id: "diagnostic_expert", family: "sante", name: "Expert du diagnostic", description: "Tu as répondu à de nombreuses questions de Bloom.", icon: "🩺", sortOrder: 34 },
  { id: "attentive_observer", family: "sante", name: "Observateur attentif", description: "Tu remarques les petits changements.", icon: "👀", sortOrder: 35 },
  // Environnement
  { id: "first_orientation", family: "environnement", name: "Première orientation", description: "Tu as renseigné l'orientation d'une fenêtre.", icon: "🧭", sortOrder: 36 },
  { id: "first_compass", family: "environnement", name: "Premier boussole", description: "Tu as utilisé la boussole pour la première fois.", icon: "🧭", sortOrder: 37 },
  { id: "perfect_placement", family: "environnement", name: "Placement parfait", description: "Une plante a trouvé un emplacement très compatible.", icon: "📍", sortOrder: 38 },
  { id: "light_master", family: "environnement", name: "Maître de la lumière", description: "Tu maîtrises les besoins en lumière de tes plantes.", icon: "☀️", sortOrder: 39 },
  { id: "garden_well_settled", family: "environnement", name: "Jardin bien installé", description: "Toutes tes plantes ont un emplacement renseigné.", icon: "🏡", sortOrder: 40 },
  // Exploration
  { id: "first_discovery", family: "exploration", name: "Première découverte", description: "Tu as consulté ta première fiche espèce.", icon: "🔎", sortOrder: 41 },
  { id: "species_10", family: "exploration", name: "10 espèces découvertes", description: "10 fiches espèces consultées.", icon: "📖", sortOrder: 42 },
  { id: "species_25", family: "exploration", name: "25 espèces découvertes", description: "25 fiches espèces consultées.", icon: "📖", sortOrder: 43 },
  { id: "species_50", family: "exploration", name: "50 espèces découvertes", description: "50 fiches espèces consultées.", icon: "📖", sortOrder: 44 },
  { id: "species_100", family: "exploration", name: "100 espèces découvertes", description: "100 fiches espèces consultées.", icon: "📖", sortOrder: 45 },
  { id: "botanical_explorer", family: "exploration", name: "Explorateur botanique", description: "Un vrai passionné de botanique.", icon: "🧑‍🌾", sortOrder: 46 },
  // Jardin virtuel
  { id: "first_garden_item", family: "jardin_virtuel", name: "Premier élément débloqué", description: "Ton jardin virtuel a reçu son premier élément.", icon: "🔓", sortOrder: 47 },
  { id: "first_tree", family: "jardin_virtuel", name: "Premier arbre", description: "Un arbre a poussé dans ton jardin.", icon: "🌳", sortOrder: 48 },
  { id: "first_bush", family: "jardin_virtuel", name: "Premier massif", description: "Un massif de fleurs a fleuri.", icon: "🌸", sortOrder: 49 },
  { id: "first_decoration", family: "jardin_virtuel", name: "Premier décor", description: "Un décor a rejoint ton jardin.", icon: "🏮", sortOrder: 50 },
  { id: "garden_blooming", family: "jardin_virtuel", name: "Jardin fleuri", description: "Ton jardin commence à fleurir joliment.", icon: "🌼", sortOrder: 51 },
  { id: "garden_lush", family: "jardin_virtuel", name: "Jardin luxuriant", description: "Ton jardin est luxuriant.", icon: "🌿", sortOrder: 52 },
  { id: "garden_extraordinary", family: "jardin_virtuel", name: "Jardin extraordinaire", description: "Un jardin extraordinaire, à ton image.", icon: "⛲", sortOrder: 53 },
  // Saisonniers
  { id: "season_spring", family: "saisonniers", name: "Printemps", description: "Tu as traversé un printemps avec Bloom.", icon: "🌷", sortOrder: 54 },
  { id: "season_summer", family: "saisonniers", name: "Été", description: "Tu as traversé un été avec Bloom.", icon: "🌻", sortOrder: 55 },
  { id: "season_autumn", family: "saisonniers", name: "Automne", description: "Tu as traversé un automne avec Bloom.", icon: "🍂", sortOrder: 56 },
  { id: "season_winter", family: "saisonniers", name: "Hiver", description: "Tu as traversé un hiver avec Bloom.", icon: "❄️", sortOrder: 57 },
  { id: "one_year", family: "saisonniers", name: "Une année au jardin", description: "Une année complète passée avec ton jardin.", icon: "🎂", sortOrder: 58 },
];

const SPECIES: Array<Parameters<typeof prisma.plantSpecies.create>[0]["data"]> = [
  {
    commonName: "Monstera",
    scientificName: "Monstera deliciosa",
    family: "Araceae",
    origin: "Amérique centrale",
    category: PlantCategory.tropicales,
    light: "Lumière vive et indirecte",
    temperatureRange: "18-27°C",
    humidity: "Moyenne à élevée",
    watering: "Quand les 3 premiers cm de substrat sont secs",
    fertilizing: "Engrais liquide toutes les 4 semaines en saison de croissance",
    pruning: "Retirer les feuilles jaunies ou abîmées",
    repotting: "Tous les 2 ans, pot légèrement plus grand",
    propagation: "Bouturage de tige avec nœud aérien",
    commonProblems: ["Feuilles jaunes (excès d'eau)", "Bords bruns (air trop sec)"],
    pests: ["Cochenilles", "Araignées rouges"],
    toxicity: "Toxique pour chats et chiens si ingérée",
    difficulty: "facile",
    petSafe: false,
    indoorOutdoor: "interieur",
    imageUrl: "/plants/placeholder-monstera.svg",
  },
  {
    commonName: "Calathea",
    scientificName: "Calathea orbifolia",
    family: "Marantaceae",
    origin: "Amérique du Sud",
    category: PlantCategory.tropicales,
    light: "Lumière indirecte, jamais de soleil direct",
    temperatureRange: "18-24°C",
    humidity: "Élevée",
    watering: "Substrat toujours légèrement humide, eau non calcaire",
    fertilizing: "Engrais dilué toutes les 4-6 semaines en saison",
    pruning: "Retirer les feuilles fanées à la base",
    repotting: "Chaque printemps, pot large et peu profond",
    propagation: "Division de touffe",
    commonProblems: ["Bords secs (air trop sec)", "Feuilles qui s'enroulent le soir (normal)"],
    pests: ["Araignées rouges"],
    toxicity: "Non toxique",
    difficulty: "modere",
    petSafe: true,
    indoorOutdoor: "interieur",
    imageUrl: "/plants/placeholder-calathea.svg",
  },
  {
    commonName: "Basilic",
    scientificName: "Ocimum basilicum",
    family: "Lamiaceae",
    origin: "Asie tropicale",
    category: PlantCategory.aromatiques,
    light: "Plein soleil à mi-ombre",
    temperatureRange: "18-30°C",
    humidity: "Moyenne",
    watering: "Substrat frais mais bien drainé, arrosage régulier",
    fertilizing: "Engrais léger toutes les 3 semaines",
    pruning: "Pincer les fleurs pour prolonger la production de feuilles",
    repotting: "Rarement nécessaire (culture souvent annuelle)",
    propagation: "Semis ou bouturage de tige dans l'eau",
    commonProblems: ["Feuilles qui jaunissent (excès d'eau)", "Montée en fleurs rapide (manque de pincement)"],
    pests: ["Pucerons"],
    toxicity: "Non toxique — comestible",
    difficulty: "facile",
    petSafe: true,
    indoorOutdoor: "les-deux",
    imageUrl: "/plants/placeholder-basilic.svg",
  },
  {
    commonName: "Citronnier",
    scientificName: "Citrus limon",
    family: "Rutaceae",
    origin: "Asie",
    category: PlantCategory.fruits,
    light: "Plein soleil",
    temperatureRange: "15-25°C, protéger en dessous de 5°C",
    humidity: "Moyenne",
    watering: "Laisser sécher légèrement entre deux arrosages",
    fertilizing: "Engrais pour agrumes toutes les 3-4 semaines en saison",
    pruning: "Tailler après la fructification pour aérer",
    repotting: "Tous les 2-3 ans, terreau drainant",
    propagation: "Bouturage semi-ligneux ou greffe",
    commonProblems: ["Chute de feuilles (courant d'air froid)", "Fruits qui tombent jeunes (stress hydrique)"],
    pests: ["Cochenilles", "Pucerons"],
    toxicity: "Feuilles légèrement toxiques pour les animaux",
    difficulty: "modere",
    petSafe: false,
    indoorOutdoor: "les-deux",
    imageUrl: "/plants/placeholder-citronnier.svg",
  },
  {
    commonName: "Echeveria",
    scientificName: "Echeveria elegans",
    family: "Crassulaceae",
    origin: "Mexique",
    category: PlantCategory.succulentes,
    light: "Plein soleil à lumière très vive",
    temperatureRange: "15-26°C",
    humidity: "Faible",
    watering: "Laisser sécher complètement le substrat entre deux arrosages",
    fertilizing: "Engrais pour succulentes toutes les 6-8 semaines en saison",
    pruning: "Retirer les feuilles sèches à la base",
    repotting: "Tous les 2 ans, terreau très drainant",
    propagation: "Bouturage de feuille ou de rosette",
    commonProblems: ["Feuilles molles (excès d'eau)", "Étiolement (manque de lumière)"],
    pests: ["Cochenilles farineuses"],
    toxicity: "Non toxique",
    difficulty: "facile",
    petSafe: true,
    indoorOutdoor: "interieur",
    imageUrl: null,
  },
  {
    commonName: "Aloe vera",
    scientificName: "Aloe vera",
    family: "Asphodelaceae",
    origin: "Péninsule arabique",
    category: PlantCategory.succulentes,
    light: "Lumière vive, plein soleil toléré",
    temperatureRange: "16-25°C",
    humidity: "Faible",
    watering: "Arroser en profondeur puis laisser sécher totalement",
    fertilizing: "Engrais pour succulentes 1 à 2 fois en saison de croissance",
    pruning: "Retirer les feuilles abîmées à la base",
    repotting: "Tous les 2-3 ans, pot large et peu profond",
    propagation: "Séparation des rejets",
    commonProblems: ["Pourriture des racines (excès d'eau)", "Feuilles pâles (manque de lumière)"],
    pests: ["Cochenilles"],
    toxicity: "Non toxique en usage topique, à éviter en ingestion pour les animaux",
    difficulty: "facile",
    petSafe: false,
    indoorOutdoor: "interieur",
    imageUrl: null,
  },
  {
    commonName: "Kentia",
    scientificName: "Howea forsteriana",
    family: "Arecaceae",
    origin: "Île Lord Howe (Australie)",
    category: PlantCategory.palmiers,
    light: "Lumière vive et indirecte, tolère la mi-ombre",
    temperatureRange: "16-24°C",
    humidity: "Moyenne",
    watering: "Maintenir le substrat légèrement humide sans excès",
    fertilizing: "Engrais pour palmiers toutes les 4 semaines en saison",
    pruning: "Retirer les palmes sèches ou jaunies",
    repotting: "Tous les 2-3 ans, pot profond",
    propagation: "Semis (lent), division rare",
    commonProblems: ["Pointes brunes (air sec)", "Jaunissement (excès d'eau)"],
    pests: ["Araignées rouges", "Cochenilles"],
    toxicity: "Non toxique",
    difficulty: "modere",
    petSafe: true,
    indoorOutdoor: "interieur",
    imageUrl: null,
  },
  {
    commonName: "Chamaedorea",
    scientificName: "Chamaedorea elegans",
    family: "Arecaceae",
    origin: "Mexique, Amérique centrale",
    category: PlantCategory.palmiers,
    light: "Lumière indirecte, tolère la faible luminosité",
    temperatureRange: "18-24°C",
    humidity: "Moyenne à élevée",
    watering: "Garder le substrat frais, éviter la stagnation d'eau",
    fertilizing: "Engrais léger toutes les 4-6 semaines en saison",
    pruning: "Retirer les palmes sèches",
    repotting: "Tous les 2 ans, pot légèrement plus grand",
    propagation: "Semis, division de touffe",
    commonProblems: ["Pointes brunes (air sec)", "Jaunissement (excès de lumière directe)"],
    pests: ["Araignées rouges"],
    toxicity: "Non toxique",
    difficulty: "facile",
    petSafe: true,
    indoorOutdoor: "interieur",
    imageUrl: null,
  },
  {
    commonName: "Orchidée Phalaenopsis",
    scientificName: "Phalaenopsis amabilis",
    family: "Orchidaceae",
    origin: "Asie du Sud-Est",
    category: PlantCategory.fleuries,
    light: "Lumière vive et indirecte, jamais de soleil direct",
    temperatureRange: "18-26°C",
    humidity: "Élevée",
    watering: "Tremper les racines 10 min une fois par semaine, bien égoutter",
    fertilizing: "Engrais spécial orchidées dilué toutes les 2-3 semaines en floraison",
    pruning: "Couper la hampe florale fanée au-dessus d'un nœud",
    repotting: "Tous les 1-2 ans, substrat spécial orchidées (écorce)",
    propagation: "Division de keiki (rejet)",
    commonProblems: ["Boutons qui tombent (courant d'air)", "Racines molles (excès d'eau)"],
    pests: ["Cochenilles"],
    toxicity: "Non toxique",
    difficulty: "modere",
    petSafe: true,
    indoorOutdoor: "interieur",
    imageUrl: null,
  },
  {
    commonName: "Rosier",
    scientificName: "Rosa spp.",
    family: "Rosaceae",
    origin: "Hémisphère nord (cultivars)",
    category: PlantCategory.fleuries,
    light: "Plein soleil, au moins 6h par jour",
    temperatureRange: "5-30°C (rusticité selon variété)",
    humidity: "Moyenne",
    watering: "Arrosage régulier au pied, éviter de mouiller le feuillage",
    fertilizing: "Engrais pour rosiers au printemps et après chaque floraison",
    pruning: "Taille de formation en fin d'hiver, retrait des fleurs fanées",
    repotting: "Rarement nécessaire en pleine terre, tous les 2-3 ans en pot",
    propagation: "Bouturage de tige, greffe",
    commonProblems: ["Taches noires (maladie fongique)", "Oïdium (air trop confiné)"],
    pests: ["Pucerons", "Araignées rouges"],
    toxicity: "Non toxique",
    difficulty: "modere",
    petSafe: true,
    indoorOutdoor: "exterieur",
    imageUrl: null,
  },
  {
    commonName: "Menthe",
    scientificName: "Mentha spicata",
    family: "Lamiaceae",
    origin: "Bassin méditerranéen",
    category: PlantCategory.aromatiques,
    light: "Mi-ombre à lumière vive",
    temperatureRange: "15-25°C",
    humidity: "Moyenne à élevée",
    watering: "Garder le substrat toujours frais, arrosage fréquent",
    fertilizing: "Engrais léger toutes les 3-4 semaines en saison",
    pruning: "Pincer régulièrement pour favoriser la ramification",
    repotting: "Chaque printemps, la menthe s'étale vite",
    propagation: "Bouturage de tige dans l'eau, division de touffe",
    commonProblems: ["Feuilles qui jaunissent (manque d'eau)", "Oïdium (air confiné)"],
    pests: ["Pucerons"],
    toxicity: "Non toxique — comestible",
    difficulty: "facile",
    petSafe: true,
    indoorOutdoor: "les-deux",
    imageUrl: null,
  },
  {
    commonName: "Tomate",
    scientificName: "Solanum lycopersicum",
    family: "Solanaceae",
    origin: "Amérique du Sud",
    category: PlantCategory.potager,
    light: "Plein soleil, au moins 6-8h par jour",
    temperatureRange: "18-27°C",
    humidity: "Moyenne",
    watering: "Arrosage régulier et constant au pied, éviter le feuillage",
    fertilizing: "Engrais pour tomates riche en potasse toutes les 2 semaines",
    pruning: "Retirer les gourmands, tuteurer la tige principale",
    repotting: "Culture annuelle, pas de rempotage",
    propagation: "Semis au printemps",
    commonProblems: ["Mildiou (humidité excessive)", "Cul noir (arrosage irrégulier)"],
    pests: ["Pucerons", "Aleurodes"],
    toxicity: "Plante toxique (hors fruit mûr), fruit comestible",
    difficulty: "modere",
    petSafe: false,
    indoorOutdoor: "les-deux",
    imageUrl: null,
  },
  {
    commonName: "Fraisier",
    scientificName: "Fragaria × ananassa",
    family: "Rosaceae",
    origin: "Hybride horticole",
    category: PlantCategory.potager,
    light: "Plein soleil à mi-ombre",
    temperatureRange: "10-25°C",
    humidity: "Moyenne",
    watering: "Arroser régulièrement sans détremper, au pied",
    fertilizing: "Engrais pour petits fruits au printemps et en été",
    pruning: "Retirer les stolons pour concentrer l'énergie sur les fruits",
    repotting: "Chaque année ou tous les 2 ans",
    propagation: "Séparation des stolons",
    commonProblems: ["Pourriture grise (humidité stagnante)", "Fruits petits (manque de soleil)"],
    pests: ["Limaces", "Pucerons"],
    toxicity: "Non toxique — comestible",
    difficulty: "facile",
    petSafe: true,
    indoorOutdoor: "les-deux",
    imageUrl: null,
  },
  {
    commonName: "Figuier",
    scientificName: "Ficus carica",
    family: "Moraceae",
    origin: "Bassin méditerranéen",
    category: PlantCategory.fruits,
    light: "Plein soleil",
    temperatureRange: "10-30°C, protéger en dessous de -10°C",
    humidity: "Moyenne",
    watering: "Arrosage régulier en été, réduire en hiver",
    fertilizing: "Engrais fruitier au printemps et en été",
    pruning: "Tailler en hiver pour aérer la ramure",
    repotting: "Tous les 2-3 ans en pot, terreau riche et drainant",
    propagation: "Bouturage de bois sec en hiver",
    commonProblems: ["Chute des figues (stress hydrique)", "Feuilles jaunes (excès d'eau)"],
    pests: ["Cochenilles", "Pucerons"],
    toxicity: "Sève irritante au contact de la peau",
    difficulty: "facile",
    petSafe: true,
    indoorOutdoor: "les-deux",
    imageUrl: null,
  },
  {
    commonName: "Olivier",
    scientificName: "Olea europaea",
    family: "Oleaceae",
    origin: "Bassin méditerranéen",
    category: PlantCategory.arbres,
    light: "Plein soleil",
    temperatureRange: "10-30°C, protéger en dessous de -5°C",
    humidity: "Faible",
    watering: "Laisser sécher entre deux arrosages, résiste à la sécheresse",
    fertilizing: "Engrais pour oliviers au printemps et en été",
    pruning: "Tailler en fin d'hiver pour aérer le centre",
    repotting: "Tous les 3-4 ans, terreau très drainant",
    propagation: "Bouturage semi-ligneux, greffe",
    commonProblems: ["Feuilles qui jaunissent (excès d'eau)", "Absence de fructification (manque de soleil)"],
    pests: ["Cochenilles", "Mouche de l'olive (extérieur)"],
    toxicity: "Non toxique",
    difficulty: "facile",
    petSafe: true,
    indoorOutdoor: "les-deux",
    imageUrl: null,
  },
  {
    commonName: "Érable du Japon",
    scientificName: "Acer palmatum",
    family: "Sapindaceae",
    origin: "Japon, Corée, Chine",
    category: PlantCategory.arbres,
    light: "Mi-ombre, protégé du soleil brûlant de l'après-midi",
    temperatureRange: "-15 à 25°C",
    humidity: "Moyenne",
    watering: "Garder le substrat frais, sensible à la sécheresse",
    fertilizing: "Engrais pour arbustes au printemps",
    pruning: "Taille légère en hiver pour équilibrer la silhouette",
    repotting: "Tous les 2-3 ans en pot, terreau de bruyère",
    propagation: "Bouturage semi-ligneux, greffe",
    commonProblems: ["Feuilles brûlées (soleil trop direct)", "Dessèchement des extrémités (vent, sécheresse)"],
    pests: ["Pucerons"],
    toxicity: "Non toxique",
    difficulty: "modere",
    petSafe: true,
    indoorOutdoor: "exterieur",
    imageUrl: null,
  },
  {
    commonName: "Hortensia",
    scientificName: "Hydrangea macrophylla",
    family: "Hydrangeaceae",
    origin: "Asie de l'Est",
    category: PlantCategory.arbustes,
    light: "Mi-ombre, lumière filtrée",
    temperatureRange: "5-25°C",
    humidity: "Élevée",
    watering: "Arrosage abondant et régulier, ne doit jamais sécher complètement",
    fertilizing: "Engrais pour hortensias au printemps et en été",
    pruning: "Tailler les fleurs fanées, taille de formation en fin d'hiver",
    repotting: "Tous les 2 ans en pot, terreau de bruyère",
    propagation: "Bouturage de tige en été",
    commonProblems: ["Feuilles flétries (manque d'eau)", "Jaunissement (chlorose sur sol calcaire)"],
    pests: ["Pucerons", "Araignées rouges"],
    toxicity: "Toxique si ingéré",
    difficulty: "modere",
    petSafe: false,
    indoorOutdoor: "exterieur",
    imageUrl: null,
  },
  {
    commonName: "Camélia",
    scientificName: "Camellia japonica",
    family: "Theaceae",
    origin: "Asie de l'Est",
    category: PlantCategory.arbustes,
    light: "Lumière vive, mi-ombre, à l'abri du soleil de midi",
    temperatureRange: "5-25°C",
    humidity: "Élevée",
    watering: "Substrat toujours légèrement humide, eau non calcaire",
    fertilizing: "Engrais pour plantes de terre de bruyère après floraison",
    pruning: "Tailler juste après la floraison si besoin",
    repotting: "Tous les 2-3 ans, terreau de bruyère acide",
    propagation: "Bouturage semi-ligneux en été",
    commonProblems: ["Boutons qui tombent (stress hydrique ou froid)", "Feuilles jaunes (sol trop calcaire)"],
    pests: ["Cochenilles"],
    toxicity: "Non toxique",
    difficulty: "modere",
    petSafe: true,
    indoorOutdoor: "les-deux",
    imageUrl: null,
  },
  {
    commonName: "Lierre",
    scientificName: "Hedera helix",
    family: "Araliaceae",
    origin: "Europe",
    category: PlantCategory.grimpantes,
    light: "Lumière indirecte à mi-ombre",
    temperatureRange: "10-24°C",
    humidity: "Moyenne",
    watering: "Laisser sécher le dessus du substrat entre deux arrosages",
    fertilizing: "Engrais léger toutes les 4-6 semaines en saison",
    pruning: "Tailler pour contrôler la croissance et densifier",
    repotting: "Tous les 2 ans, pot légèrement plus grand",
    propagation: "Bouturage de tige dans l'eau",
    commonProblems: ["Feuilles jaunes (excès d'eau)", "Étiolement (manque de lumière)"],
    pests: ["Araignées rouges", "Cochenilles"],
    toxicity: "Toxique si ingéré",
    difficulty: "facile",
    petSafe: false,
    indoorOutdoor: "les-deux",
    imageUrl: null,
  },
  {
    commonName: "Jasmin étoilé",
    scientificName: "Jasminum polyanthum",
    family: "Oleaceae",
    origin: "Chine",
    category: PlantCategory.grimpantes,
    light: "Lumière vive, quelques heures de soleil direct appréciées",
    temperatureRange: "12-24°C",
    humidity: "Moyenne",
    watering: "Arrosage régulier, laisser sécher légèrement en surface",
    fertilizing: "Engrais pour plantes fleuries toutes les 3-4 semaines en saison",
    pruning: "Tailler après la floraison pour maîtriser le volume",
    repotting: "Tous les 2 ans, pot avec support à grimper",
    propagation: "Bouturage semi-ligneux",
    commonProblems: ["Absence de floraison (manque de lumière ou de fraîcheur hivernale)", "Chute de feuilles (courant d'air froid)"],
    pests: ["Pucerons", "Cochenilles"],
    toxicity: "Non toxique",
    difficulty: "modere",
    petSafe: true,
    indoorOutdoor: "les-deux",
    imageUrl: null,
  },
  {
    commonName: "Pothos",
    scientificName: "Epipremnum aureum",
    family: "Araceae",
    origin: "Îles Salomon",
    category: PlantCategory.retombantes,
    light: "Lumière indirecte, tolère la faible luminosité",
    temperatureRange: "18-27°C",
    humidity: "Moyenne",
    watering: "Laisser sécher les 2-3 premiers cm de substrat entre deux arrosages",
    fertilizing: "Engrais léger toutes les 4-6 semaines en saison",
    pruning: "Pincer les tiges pour densifier",
    repotting: "Tous les 2 ans, pot légèrement plus grand",
    propagation: "Bouturage de tige dans l'eau",
    commonProblems: ["Feuilles jaunes (excès d'eau)", "Feuilles pâles (manque de lumière)"],
    pests: ["Cochenilles"],
    toxicity: "Toxique si ingéré",
    difficulty: "facile",
    petSafe: false,
    indoorOutdoor: "interieur",
    imageUrl: null,
  },
  {
    commonName: "Chlorophytum",
    scientificName: "Chlorophytum comosum",
    family: "Asparagaceae",
    origin: "Afrique du Sud",
    category: PlantCategory.retombantes,
    light: "Lumière vive et indirecte, tolère la mi-ombre",
    temperatureRange: "15-24°C",
    humidity: "Moyenne",
    watering: "Arrosage régulier, laisser sécher légèrement en surface",
    fertilizing: "Engrais léger toutes les 4-6 semaines en saison",
    pruning: "Retirer les feuilles sèches, couper les stolons si besoin",
    repotting: "Chaque année, pousse vite",
    propagation: "Séparation des plantules sur les stolons",
    commonProblems: ["Pointes brunes (eau calcaire ou air sec)", "Feuilles pâles (excès de soleil direct)"],
    pests: ["Cochenilles"],
    toxicity: "Non toxique",
    difficulty: "facile",
    petSafe: true,
    indoorOutdoor: "interieur",
    imageUrl: null,
  },
  {
    commonName: "Lavande",
    scientificName: "Lavandula angustifolia",
    family: "Lamiaceae",
    origin: "Bassin méditerranéen",
    category: PlantCategory.mediterraneennes,
    light: "Plein soleil",
    temperatureRange: "5-30°C",
    humidity: "Faible",
    watering: "Laisser sécher complètement entre deux arrosages, résiste à la sécheresse",
    fertilizing: "Peu exigeante, engrais léger au printemps suffit",
    pruning: "Tailler après la floraison pour garder une silhouette compacte",
    repotting: "Tous les 2-3 ans, terreau très drainant, sableux",
    propagation: "Bouturage semi-ligneux en été",
    commonProblems: ["Pourriture des racines (excès d'eau)", "Floraison faible (manque de soleil)"],
    pests: ["Cicadelles"],
    toxicity: "Non toxique",
    difficulty: "facile",
    petSafe: true,
    indoorOutdoor: "les-deux",
    imageUrl: null,
  },
  {
    commonName: "Romarin",
    scientificName: "Salvia rosmarinus",
    family: "Lamiaceae",
    origin: "Bassin méditerranéen",
    category: PlantCategory.mediterraneennes,
    light: "Plein soleil",
    temperatureRange: "10-30°C",
    humidity: "Faible",
    watering: "Laisser sécher entre deux arrosages, résiste bien à la sécheresse",
    fertilizing: "Engrais léger au printemps",
    pruning: "Tailler légèrement après floraison pour densifier",
    repotting: "Tous les 2-3 ans, terreau drainant",
    propagation: "Bouturage semi-ligneux, semis",
    commonProblems: ["Jaunissement (excès d'eau)", "Base qui se dégarnit (manque de taille)"],
    pests: ["Cicadelles", "Pucerons"],
    toxicity: "Non toxique — comestible",
    difficulty: "facile",
    petSafe: true,
    indoorOutdoor: "les-deux",
    imageUrl: null,
  },
  {
    commonName: "Géranium",
    scientificName: "Pelargonium spp.",
    family: "Geraniaceae",
    origin: "Afrique du Sud",
    category: PlantCategory.jardin,
    light: "Plein soleil à mi-ombre",
    temperatureRange: "10-25°C",
    humidity: "Moyenne",
    watering: "Laisser sécher légèrement entre deux arrosages",
    fertilizing: "Engrais pour plantes fleuries toutes les 2 semaines en saison",
    pruning: "Retirer les fleurs et feuilles fanées régulièrement",
    repotting: "Chaque printemps, terreau riche et drainant",
    propagation: "Bouturage de tige",
    commonProblems: ["Feuilles jaunes (excès d'eau)", "Peu de fleurs (manque de lumière)"],
    pests: ["Chenilles", "Pucerons"],
    toxicity: "Légèrement toxique si ingéré",
    difficulty: "facile",
    petSafe: false,
    indoorOutdoor: "les-deux",
    imageUrl: null,
  },
  {
    commonName: "Marguerite",
    scientificName: "Leucanthemum vulgare",
    family: "Asteraceae",
    origin: "Europe",
    category: PlantCategory.jardin,
    light: "Plein soleil à mi-ombre",
    temperatureRange: "5-25°C",
    humidity: "Moyenne",
    watering: "Arrosage régulier sans excès, résiste à de courtes sécheresses",
    fertilizing: "Engrais pour plantes fleuries en début de saison",
    pruning: "Retirer les fleurs fanées pour prolonger la floraison",
    repotting: "Tous les 2 ans en pot, sinon pleine terre",
    propagation: "Division de touffe, semis",
    commonProblems: ["Peu de fleurs (manque de soleil)", "Tiges qui versent (manque de lumière)"],
    pests: ["Pucerons", "Limaces"],
    toxicity: "Non toxique",
    difficulty: "facile",
    petSafe: true,
    indoorOutdoor: "les-deux",
    imageUrl: null,
  },
  {
    commonName: "Tulipe",
    scientificName: "Tulipa spp.",
    family: "Liliaceae",
    origin: "Asie centrale",
    category: PlantCategory.bulbes,
    light: "Plein soleil à mi-ombre",
    temperatureRange: "5-20°C",
    humidity: "Moyenne",
    watering: "Arrosage modéré, éviter l'eau stagnante autour du bulbe",
    fertilizing: "Engrais pour bulbes à la plantation, peu nécessaire ensuite",
    pruning: "Retirer la fleur fanée, laisser le feuillage jaunir naturellement",
    repotting: "Replantation annuelle ou tous les 2-3 ans",
    propagation: "Division des bulbilles",
    commonProblems: ["Pourriture du bulbe (excès d'eau)", "Absence de floraison (bulbe pas assez froid en hiver)"],
    pests: ["Pucerons"],
    toxicity: "Toxique si ingéré (bulbe surtout)",
    difficulty: "facile",
    petSafe: false,
    indoorOutdoor: "les-deux",
    imageUrl: null,
  },
  {
    commonName: "Jacinthe",
    scientificName: "Hyacinthus orientalis",
    family: "Asparagaceae",
    origin: "Bassin méditerranéen oriental",
    category: PlantCategory.bulbes,
    light: "Lumière vive, plein soleil en extérieur",
    temperatureRange: "5-18°C",
    humidity: "Moyenne",
    watering: "Arrosage modéré, laisser sécher légèrement entre deux",
    fertilizing: "Engrais léger pendant la croissance, peu nécessaire",
    pruning: "Retirer la hampe florale fanée",
    repotting: "Replantation annuelle du bulbe",
    propagation: "Division des bulbilles",
    commonProblems: ["Pourriture du bulbe (excès d'eau)", "Tiges molles (chaleur excessive)"],
    pests: ["Pucerons"],
    toxicity: "Toxique si ingéré",
    difficulty: "facile",
    petSafe: false,
    indoorOutdoor: "les-deux",
    imageUrl: null,
  },
  {
    commonName: "Fougère de Boston",
    scientificName: "Nephrolepis exaltata",
    family: "Nephrolepidaceae",
    origin: "Régions tropicales",
    category: PlantCategory.fougeres,
    light: "Lumière indirecte, jamais de soleil direct",
    temperatureRange: "16-24°C",
    humidity: "Élevée",
    watering: "Garder le substrat toujours légèrement humide",
    fertilizing: "Engrais léger toutes les 4-6 semaines en saison",
    pruning: "Retirer les frondes sèches ou jaunies",
    repotting: "Chaque printemps, pot large",
    propagation: "Division de touffe",
    commonProblems: ["Frondes brunes (air trop sec)", "Pourriture (excès d'eau stagnante)"],
    pests: ["Cochenilles"],
    toxicity: "Non toxique",
    difficulty: "modere",
    petSafe: true,
    indoorOutdoor: "interieur",
    imageUrl: null,
  },
  {
    commonName: "Capillaire",
    scientificName: "Adiantum raddianum",
    family: "Pteridaceae",
    origin: "Amérique tropicale",
    category: PlantCategory.fougeres,
    light: "Lumière indirecte, ambiance humide",
    temperatureRange: "18-24°C",
    humidity: "Élevée",
    watering: "Substrat toujours humide, ne jamais laisser sécher",
    fertilizing: "Engrais très dilué toutes les 4-6 semaines",
    pruning: "Retirer les frondes sèches à la base",
    repotting: "Chaque année, terreau léger et humifère",
    propagation: "Division de touffe",
    commonProblems: ["Frondes qui sèchent (air trop sec)", "Jaunissement (eau calcaire)"],
    pests: ["Cochenilles"],
    toxicity: "Non toxique",
    difficulty: "exigeant",
    petSafe: true,
    indoorOutdoor: "interieur",
    imageUrl: null,
  },
  {
    commonName: "Dionée attrape-mouche",
    scientificName: "Dionaea muscipula",
    family: "Droseraceae",
    origin: "Caroline (États-Unis)",
    category: PlantCategory.carnivores,
    light: "Lumière très vive, plein soleil quelques heures",
    temperatureRange: "10-30°C",
    humidity: "Élevée",
    watering: "Substrat toujours humide, uniquement eau de pluie ou déminéralisée",
    fertilizing: "Aucun engrais — se nourrit d'insectes occasionnellement",
    pruning: "Retirer les pièges noircis",
    repotting: "Chaque année, substrat tourbe/sable sans calcaire",
    propagation: "Division de rhizome, semis",
    commonProblems: ["Pièges qui noircissent (déclenchements répétés à vide)", "Affaiblissement (eau calcaire)"],
    pests: ["Pucerons"],
    toxicity: "Non toxique",
    difficulty: "exigeant",
    petSafe: true,
    indoorOutdoor: "interieur",
    imageUrl: null,
  },
  {
    commonName: "Sarracénie",
    scientificName: "Sarracenia spp.",
    family: "Sarraceniaceae",
    origin: "Amérique du Nord",
    category: PlantCategory.carnivores,
    light: "Plein soleil",
    temperatureRange: "5-30°C (période de repos hivernal nécessaire)",
    humidity: "Élevée",
    watering: "Substrat toujours gorgé d'eau, uniquement eau de pluie ou déminéralisée",
    fertilizing: "Aucun engrais — se nourrit d'insectes",
    pruning: "Retirer les feuilles fanées en fin de saison",
    repotting: "Tous les 2 ans, substrat tourbe/sable",
    propagation: "Division de rhizome",
    commonProblems: ["Feuilles qui brunissent (manque de repos hivernal)", "Faible croissance (eau calcaire)"],
    pests: ["Pucerons"],
    toxicity: "Non toxique",
    difficulty: "exigeant",
    petSafe: true,
    indoorOutdoor: "les-deux",
    imageUrl: null,
  },
  {
    commonName: "Nénuphar",
    scientificName: "Nymphaea spp.",
    family: "Nymphaeaceae",
    origin: "Régions tempérées et tropicales",
    category: PlantCategory.aquatiques,
    light: "Plein soleil",
    temperatureRange: "10-28°C",
    humidity: "Aquatique",
    watering: "Toujours immergé, ne jamais laisser le bassin s'assécher",
    fertilizing: "Engrais aquatique en tablettes à la reprise de végétation",
    pruning: "Retirer les feuilles et fleurs fanées",
    repotting: "Division du rhizome tous les 3-4 ans",
    propagation: "Division de rhizome",
    commonProblems: ["Peu de floraison (manque de soleil)", "Eau trouble (déséquilibre du bassin)"],
    pests: ["Pucerons du nénuphar"],
    toxicity: "Non toxique",
    difficulty: "modere",
    petSafe: true,
    indoorOutdoor: "exterieur",
    imageUrl: null,
  },
  {
    commonName: "Jacinthe d'eau",
    scientificName: "Eichhornia crassipes",
    family: "Pontederiaceae",
    origin: "Amazonie",
    category: PlantCategory.aquatiques,
    light: "Plein soleil à mi-ombre",
    temperatureRange: "18-30°C",
    humidity: "Aquatique",
    watering: "Flotte librement à la surface, ne jamais laisser le bassin sécher",
    fertilizing: "Peu d'engrais nécessaire, eau riche en nutriments lui suffit",
    pruning: "Retirer les feuilles jaunies et limiter la prolifération",
    repotting: "Aucun rempotage — plante flottante",
    propagation: "Division des rejets",
    commonProblems: ["Feuilles jaunes (eau trop froide)", "Prolifération excessive (eau très riche)"],
    pests: ["Pucerons"],
    toxicity: "Non toxique — espèce invasive à ne jamais relâcher en milieu naturel",
    difficulty: "facile",
    petSafe: true,
    indoorOutdoor: "exterieur",
    imageUrl: null,
  },
  {
    commonName: "Ficus Ginseng",
    scientificName: "Ficus microcarpa",
    family: "Moraceae",
    origin: "Asie du Sud-Est",
    category: PlantCategory.bonsais,
    light: "Lumière vive et indirecte",
    temperatureRange: "18-26°C",
    humidity: "Moyenne",
    watering: "Laisser sécher légèrement le dessus du substrat entre deux arrosages",
    fertilizing: "Engrais pour bonsaïs toutes les 4 semaines en saison",
    pruning: "Taille régulière pour maintenir la forme miniature",
    repotting: "Tous les 2 ans, terreau spécial bonsaï",
    propagation: "Bouturage, marcottage",
    commonProblems: ["Chute de feuilles (courant d'air ou changement brusque)", "Racines molles (excès d'eau)"],
    pests: ["Cochenilles", "Araignées rouges"],
    toxicity: "Sève légèrement irritante",
    difficulty: "modere",
    petSafe: false,
    indoorOutdoor: "interieur",
    imageUrl: null,
  },
  {
    commonName: "Orme de Chine",
    scientificName: "Ulmus parvifolia",
    family: "Ulmaceae",
    origin: "Asie de l'Est",
    category: PlantCategory.bonsais,
    light: "Lumière vive, quelques heures de soleil direct",
    temperatureRange: "5-25°C",
    humidity: "Moyenne",
    watering: "Substrat toujours légèrement humide, ne jamais sécher complètement",
    fertilizing: "Engrais pour bonsaïs toutes les 4 semaines en saison",
    pruning: "Taille fréquente pour maintenir la ramification fine",
    repotting: "Tous les 2 ans, terreau spécial bonsaï",
    propagation: "Bouturage, marcottage",
    commonProblems: ["Chute de feuilles (stress hydrique)", "Faible ramification (manque de taille)"],
    pests: ["Pucerons"],
    toxicity: "Non toxique",
    difficulty: "modere",
    petSafe: true,
    indoorOutdoor: "les-deux",
    imageUrl: null,
  },
  {
    commonName: "Haworthia",
    scientificName: "Haworthia fasciata",
    family: "Asphodelaceae",
    origin: "Afrique du Sud",
    category: PlantCategory.succulentes,
    light: "Lumière vive et indirecte, éviter le plein soleil brûlant",
    temperatureRange: "15-24°C",
    humidity: "Faible",
    watering: "Laisser sécher complètement le substrat entre deux arrosages",
    fertilizing: "Engrais pour succulentes 1 à 2 fois en saison de croissance",
    pruning: "Retirer les feuilles sèches à la base",
    repotting: "Tous les 2-3 ans, terreau très drainant",
    propagation: "Séparation des rejets",
    commonProblems: ["Pourriture (excès d'eau)", "Taches (soleil direct trop fort)"],
    pests: ["Cochenilles farineuses"],
    toxicity: "Non toxique",
    difficulty: "facile",
    petSafe: true,
    indoorOutdoor: "interieur",
    imageUrl: null,
  },
  {
    commonName: "Arbre de jouvence",
    scientificName: "Crassula ovata",
    family: "Crassulaceae",
    origin: "Afrique du Sud",
    category: PlantCategory.succulentes,
    light: "Lumière vive, quelques heures de soleil direct",
    temperatureRange: "15-24°C",
    humidity: "Faible",
    watering: "Laisser sécher complètement entre deux arrosages",
    fertilizing: "Engrais pour succulentes toutes les 6-8 semaines en saison",
    pruning: "Tailler pour équilibrer la silhouette arbustive",
    repotting: "Tous les 2-3 ans, terreau très drainant",
    propagation: "Bouturage de feuille ou de tige",
    commonProblems: ["Chute de feuilles (excès d'eau)", "Tiges qui s'étiolent (manque de lumière)"],
    pests: ["Cochenilles farineuses"],
    toxicity: "Légèrement toxique pour les animaux",
    difficulty: "facile",
    petSafe: false,
    indoorOutdoor: "interieur",
    imageUrl: null,
  },
  {
    commonName: "Areca",
    scientificName: "Dypsis lutescens",
    family: "Arecaceae",
    origin: "Madagascar",
    category: PlantCategory.palmiers,
    light: "Lumière vive et indirecte",
    temperatureRange: "18-24°C",
    humidity: "Moyenne à élevée",
    watering: "Maintenir le substrat légèrement humide sans excès",
    fertilizing: "Engrais pour palmiers toutes les 4 semaines en saison",
    pruning: "Retirer les palmes sèches",
    repotting: "Tous les 2-3 ans, pot profond",
    propagation: "Division de touffe",
    commonProblems: ["Pointes brunes (air sec)", "Jaunissement (eau calcaire)"],
    pests: ["Araignées rouges", "Cochenilles"],
    toxicity: "Non toxique",
    difficulty: "modere",
    petSafe: true,
    indoorOutdoor: "interieur",
    imageUrl: null,
  },
  {
    commonName: "Hibiscus",
    scientificName: "Hibiscus rosa-sinensis",
    family: "Malvaceae",
    origin: "Asie de l'Est",
    category: PlantCategory.fleuries,
    light: "Plein soleil à lumière vive",
    temperatureRange: "15-27°C",
    humidity: "Moyenne",
    watering: "Arrosage régulier, substrat toujours légèrement humide en floraison",
    fertilizing: "Engrais pour plantes fleuries toutes les 2 semaines en saison",
    pruning: "Tailler au printemps pour stimuler la floraison",
    repotting: "Tous les 2 ans, terreau riche",
    propagation: "Bouturage semi-ligneux",
    commonProblems: ["Chute de boutons (stress hydrique)", "Peu de fleurs (manque de lumière)"],
    pests: ["Pucerons", "Cochenilles"],
    toxicity: "Non toxique",
    difficulty: "modere",
    petSafe: true,
    indoorOutdoor: "les-deux",
    imageUrl: null,
  },
  {
    commonName: "Anthurium",
    scientificName: "Anthurium andraeanum",
    family: "Araceae",
    origin: "Amérique centrale",
    category: PlantCategory.fleuries,
    light: "Lumière vive et indirecte",
    temperatureRange: "18-27°C",
    humidity: "Élevée",
    watering: "Substrat légèrement humide, laisser sécher en surface entre deux arrosages",
    fertilizing: "Engrais dilué toutes les 4 semaines en saison",
    pruning: "Retirer les fleurs et feuilles fanées",
    repotting: "Tous les 2 ans, terreau aéré",
    propagation: "Division de touffe",
    commonProblems: ["Absence de floraison (manque de lumière)", "Feuilles jaunes (excès d'eau)"],
    pests: ["Cochenilles", "Araignées rouges"],
    toxicity: "Toxique si ingéré",
    difficulty: "modere",
    petSafe: false,
    indoorOutdoor: "interieur",
    imageUrl: null,
  },
  {
    commonName: "Bégonia",
    scientificName: "Begonia elatior",
    family: "Begoniaceae",
    origin: "Régions tropicales",
    category: PlantCategory.fleuries,
    light: "Lumière vive et indirecte",
    temperatureRange: "16-24°C",
    humidity: "Moyenne à élevée",
    watering: "Laisser sécher légèrement en surface entre deux arrosages",
    fertilizing: "Engrais pour plantes fleuries toutes les 2-3 semaines en saison",
    pruning: "Retirer les fleurs fanées et tiges dégarnies",
    repotting: "Chaque printemps, terreau léger",
    propagation: "Bouturage de tige ou de feuille",
    commonProblems: ["Oïdium (air confiné)", "Pourriture (excès d'eau)"],
    pests: ["Pucerons", "Cochenilles"],
    toxicity: "Toxique si ingéré",
    difficulty: "modere",
    petSafe: false,
    indoorOutdoor: "interieur",
    imageUrl: null,
  },
  {
    commonName: "Thym",
    scientificName: "Thymus vulgaris",
    family: "Lamiaceae",
    origin: "Bassin méditerranéen",
    category: PlantCategory.aromatiques,
    light: "Plein soleil",
    temperatureRange: "10-30°C",
    humidity: "Faible",
    watering: "Laisser sécher entre deux arrosages, résiste à la sécheresse",
    fertilizing: "Peu exigeant, engrais léger au printemps",
    pruning: "Tailler après floraison pour garder une touffe compacte",
    repotting: "Tous les 2-3 ans, terreau drainant",
    propagation: "Bouturage semi-ligneux, semis, division",
    commonProblems: ["Pourriture des racines (excès d'eau)", "Base qui se dégarnit (manque de taille)"],
    pests: ["Pucerons"],
    toxicity: "Non toxique — comestible",
    difficulty: "facile",
    petSafe: true,
    indoorOutdoor: "les-deux",
    imageUrl: null,
  },
  {
    commonName: "Persil",
    scientificName: "Petroselinum crispum",
    family: "Apiaceae",
    origin: "Bassin méditerranéen",
    category: PlantCategory.aromatiques,
    light: "Lumière vive à mi-ombre",
    temperatureRange: "15-25°C",
    humidity: "Moyenne",
    watering: "Substrat frais, arrosage régulier",
    fertilizing: "Engrais léger toutes les 3-4 semaines",
    pruning: "Couper les tiges extérieures en premier",
    repotting: "Culture souvent annuelle ou bisannuelle",
    propagation: "Semis direct (racine pivotante fragile)",
    commonProblems: ["Montée en fleurs (chaleur, manque de récolte)", "Feuilles jaunes (manque d'eau)"],
    pests: ["Pucerons", "Chenilles"],
    toxicity: "Non toxique — comestible",
    difficulty: "facile",
    petSafe: true,
    indoorOutdoor: "les-deux",
    imageUrl: null,
  },
  {
    commonName: "Ciboulette",
    scientificName: "Allium schoenoprasum",
    family: "Amaryllidaceae",
    origin: "Hémisphère nord",
    category: PlantCategory.aromatiques,
    light: "Plein soleil à mi-ombre",
    temperatureRange: "10-25°C",
    humidity: "Moyenne",
    watering: "Substrat frais, arrosage régulier sans excès",
    fertilizing: "Engrais léger toutes les 4 semaines en saison",
    pruning: "Couper au ras pour stimuler la repousse",
    repotting: "Chaque printemps, division de touffe",
    propagation: "Division de touffe, semis",
    commonProblems: ["Feuilles jaunes (manque d'eau)", "Touffe clairsemée (besoin de division)"],
    pests: ["Pucerons"],
    toxicity: "Non toxique — comestible",
    difficulty: "facile",
    petSafe: true,
    indoorOutdoor: "les-deux",
    imageUrl: null,
  },
  {
    commonName: "Poivron",
    scientificName: "Capsicum annuum",
    family: "Solanaceae",
    origin: "Amérique centrale",
    category: PlantCategory.potager,
    light: "Plein soleil",
    temperatureRange: "18-28°C",
    humidity: "Moyenne",
    watering: "Arrosage régulier et constant, éviter les à-coups",
    fertilizing: "Engrais pour légumes-fruits toutes les 2 semaines",
    pruning: "Retirer les premières fleurs pour renforcer le plant",
    repotting: "Culture annuelle, pas de rempotage",
    propagation: "Semis au chaud au printemps",
    commonProblems: ["Chute des fleurs (chaleur excessive)", "Pourriture apicale (arrosage irrégulier)"],
    pests: ["Pucerons", "Aleurodes"],
    toxicity: "Non toxique — comestible",
    difficulty: "modere",
    petSafe: true,
    indoorOutdoor: "les-deux",
    imageUrl: null,
  },
  {
    commonName: "Courgette",
    scientificName: "Cucurbita pepo",
    family: "Cucurbitaceae",
    origin: "Amérique du Nord",
    category: PlantCategory.potager,
    light: "Plein soleil",
    temperatureRange: "18-28°C",
    humidity: "Moyenne",
    watering: "Arrosage abondant et régulier au pied",
    fertilizing: "Engrais riche en potasse toutes les 2 semaines",
    pruning: "Retirer les feuilles âgées ou malades",
    repotting: "Culture annuelle",
    propagation: "Semis direct après les dernières gelées",
    commonProblems: ["Oïdium (air humide et confiné)", "Fruits qui pourrissent (mauvaise pollinisation)"],
    pests: ["Pucerons", "Limaces"],
    toxicity: "Non toxique — comestible",
    difficulty: "facile",
    petSafe: true,
    indoorOutdoor: "exterieur",
    imageUrl: null,
  },
  {
    commonName: "Framboisier",
    scientificName: "Rubus idaeus",
    family: "Rosaceae",
    origin: "Europe, Asie",
    category: PlantCategory.fruits,
    light: "Plein soleil à mi-ombre",
    temperatureRange: "5-25°C",
    humidity: "Moyenne",
    watering: "Arrosage régulier, surtout à la fructification",
    fertilizing: "Engrais pour petits fruits au printemps",
    pruning: "Tailler les cannes ayant fructifié après récolte",
    repotting: "Rarement en pleine terre, tous les 2-3 ans en pot",
    propagation: "Rejets racinaires, bouturage",
    commonProblems: ["Pourriture grise (humidité stagnante)", "Chlorose (sol trop calcaire)"],
    pests: ["Pucerons", "Vers du framboisier"],
    toxicity: "Non toxique — comestible",
    difficulty: "facile",
    petSafe: true,
    indoorOutdoor: "exterieur",
    imageUrl: null,
  },
  {
    commonName: "Myrtillier",
    scientificName: "Vaccinium corymbosum",
    family: "Ericaceae",
    origin: "Amérique du Nord",
    category: PlantCategory.fruits,
    light: "Plein soleil à mi-ombre",
    temperatureRange: "5-25°C",
    humidity: "Moyenne à élevée",
    watering: "Substrat toujours frais, eau non calcaire",
    fertilizing: "Engrais pour plantes de terre de bruyère au printemps",
    pruning: "Tailler les branches âgées en hiver",
    repotting: "Tous les 2-3 ans, terreau de bruyère acide",
    propagation: "Bouturage semi-ligneux, marcottage",
    commonProblems: ["Chlorose (sol trop calcaire)", "Peu de fruits (manque de pollinisation croisée)"],
    pests: ["Pucerons", "Oiseaux (extérieur)"],
    toxicity: "Non toxique — comestible",
    difficulty: "modere",
    petSafe: true,
    indoorOutdoor: "exterieur",
    imageUrl: null,
  },
  {
    commonName: "Bouleau",
    scientificName: "Betula pendula",
    family: "Betulaceae",
    origin: "Europe, Asie",
    category: PlantCategory.arbres,
    light: "Plein soleil à mi-ombre",
    temperatureRange: "-20 à 25°C",
    humidity: "Moyenne",
    watering: "Arrosage régulier les premières années, puis autonome",
    fertilizing: "Engrais à la plantation, peu nécessaire ensuite",
    pruning: "Tailler en hiver pour retirer le bois mort",
    repotting: "Rarement, arbre de pleine terre",
    propagation: "Semis, greffe",
    commonProblems: ["Chlorose (sol trop calcaire)", "Puceron noir (attaque le feuillage)"],
    pests: ["Pucerons"],
    toxicity: "Non toxique",
    difficulty: "facile",
    petSafe: true,
    indoorOutdoor: "exterieur",
    imageUrl: null,
  },
  {
    commonName: "Eucalyptus",
    scientificName: "Eucalyptus gunnii",
    family: "Myrtaceae",
    origin: "Australie",
    category: PlantCategory.arbres,
    light: "Plein soleil",
    temperatureRange: "-10 à 30°C",
    humidity: "Faible",
    watering: "Laisser sécher entre deux arrosages une fois établi",
    fertilizing: "Engrais léger au printemps",
    pruning: "Tailler au printemps pour contrôler la hauteur",
    repotting: "Tous les 2-3 ans en pot, terreau drainant",
    propagation: "Semis",
    commonProblems: ["Feuilles qui jaunissent (excès d'eau)", "Croissance très rapide (besoin de taille)"],
    pests: ["Psylles de l'eucalyptus"],
    toxicity: "Feuilles toxiques si ingérées en grande quantité",
    difficulty: "facile",
    petSafe: false,
    indoorOutdoor: "les-deux",
    imageUrl: null,
  },
  {
    commonName: "Buis",
    scientificName: "Buxus sempervirens",
    family: "Buxaceae",
    origin: "Europe, Asie, Afrique du Nord",
    category: PlantCategory.arbustes,
    light: "Plein soleil à mi-ombre",
    temperatureRange: "-15 à 30°C",
    humidity: "Moyenne",
    watering: "Arrosage modéré, résiste bien à la sécheresse une fois établi",
    fertilizing: "Engrais à décomposition lente au printemps",
    pruning: "Taille de forme 1 à 2 fois par an",
    repotting: "Tous les 3-4 ans en pot",
    propagation: "Bouturage semi-ligneux",
    commonProblems: ["Pyrale du buis (chenille défoliatrice)", "Jaunissement (sol trop compact)"],
    pests: ["Pyrale du buis", "Cochenilles"],
    toxicity: "Toxique si ingéré",
    difficulty: "facile",
    petSafe: false,
    indoorOutdoor: "les-deux",
    imageUrl: null,
  },
  {
    commonName: "Laurier-rose",
    scientificName: "Nerium oleander",
    family: "Apocynaceae",
    origin: "Bassin méditerranéen",
    category: PlantCategory.arbustes,
    light: "Plein soleil",
    temperatureRange: "5-35°C, protéger en dessous de 0°C",
    humidity: "Faible",
    watering: "Arrosage régulier en été, réduire en hiver",
    fertilizing: "Engrais pour plantes fleuries toutes les 3 semaines en saison",
    pruning: "Tailler après la floraison pour contrôler le volume",
    repotting: "Tous les 2-3 ans, terreau drainant",
    propagation: "Bouturage de tige dans l'eau",
    commonProblems: ["Chute de feuilles (froid)", "Cochenilles (air trop sec en hivernage)"],
    pests: ["Cochenilles", "Pucerons"],
    toxicity: "Très toxique si ingéré (plante et sève)",
    difficulty: "facile",
    petSafe: false,
    indoorOutdoor: "les-deux",
    imageUrl: null,
  },
  {
    commonName: "Bougainvillier",
    scientificName: "Bougainvillea glabra",
    family: "Nyctaginaceae",
    origin: "Amérique du Sud",
    category: PlantCategory.grimpantes,
    light: "Plein soleil",
    temperatureRange: "10-30°C",
    humidity: "Faible",
    watering: "Laisser sécher entre deux arrosages, floraison stimulée par le stress hydrique léger",
    fertilizing: "Engrais pour plantes fleuries toutes les 2-3 semaines en saison",
    pruning: "Tailler après la floraison pour densifier",
    repotting: "Tous les 2 ans, terreau drainant",
    propagation: "Bouturage semi-ligneux",
    commonProblems: ["Chute des bractées (arrosage excessif)", "Absence de floraison (manque de lumière)"],
    pests: ["Cochenilles", "Pucerons"],
    toxicity: "Légèrement toxique, épines irritantes",
    difficulty: "modere",
    petSafe: false,
    indoorOutdoor: "les-deux",
    imageUrl: null,
  },
  {
    commonName: "Glycine",
    scientificName: "Wisteria sinensis",
    family: "Fabaceae",
    origin: "Chine",
    category: PlantCategory.grimpantes,
    light: "Plein soleil",
    temperatureRange: "-15 à 30°C",
    humidity: "Moyenne",
    watering: "Arrosage régulier les premières années, puis autonome",
    fertilizing: "Engrais pour plantes fleuries au printemps",
    pruning: "Taille sévère en hiver et légère en été pour la floraison",
    repotting: "Rarement, plante de pleine terre avec support solide",
    propagation: "Bouturage, marcottage, greffe",
    commonProblems: ["Absence de floraison (taille inadaptée)", "Chlorose (sol trop calcaire)"],
    pests: ["Pucerons"],
    toxicity: "Toxique si ingéré (graines surtout)",
    difficulty: "modere",
    petSafe: false,
    indoorOutdoor: "exterieur",
    imageUrl: null,
  },
  {
    commonName: "Misère (Tradescantia)",
    scientificName: "Tradescantia zebrina",
    family: "Commelinaceae",
    origin: "Amérique centrale",
    category: PlantCategory.retombantes,
    light: "Lumière vive et indirecte",
    temperatureRange: "15-24°C",
    humidity: "Moyenne",
    watering: "Laisser sécher légèrement en surface entre deux arrosages",
    fertilizing: "Engrais léger toutes les 4-6 semaines en saison",
    pruning: "Pincer les tiges pour densifier",
    repotting: "Chaque année, pousse vite",
    propagation: "Bouturage de tige dans l'eau",
    commonProblems: ["Perte de coloration (manque de lumière)", "Tiges dégarnies (manque de taille)"],
    pests: ["Cochenilles"],
    toxicity: "Légèrement irritant au contact",
    difficulty: "facile",
    petSafe: false,
    indoorOutdoor: "interieur",
    imageUrl: null,
  },
  {
    commonName: "Fuchsia retombant",
    scientificName: "Fuchsia × hybrida",
    family: "Onagraceae",
    origin: "Amérique du Sud",
    category: PlantCategory.retombantes,
    light: "Lumière vive, mi-ombre en été",
    temperatureRange: "10-24°C",
    humidity: "Moyenne à élevée",
    watering: "Substrat toujours légèrement humide en saison",
    fertilizing: "Engrais pour plantes fleuries toutes les 2 semaines en saison",
    pruning: "Pincer les jeunes pousses pour ramifier",
    repotting: "Chaque printemps, terreau riche",
    propagation: "Bouturage de tige",
    commonProblems: ["Chute de boutons (stress hydrique ou chaleur)", "Feuilles jaunes (excès de soleil direct)"],
    pests: ["Aleurodes", "Pucerons"],
    toxicity: "Non toxique",
    difficulty: "modere",
    petSafe: true,
    indoorOutdoor: "les-deux",
    imageUrl: null,
  },
  {
    commonName: "Ficus lyrata",
    scientificName: "Ficus lyrata",
    family: "Moraceae",
    origin: "Afrique de l'Ouest",
    category: PlantCategory.tropicales,
    light: "Lumière vive et indirecte",
    temperatureRange: "18-27°C",
    humidity: "Moyenne",
    watering: "Laisser sécher les 3-4 premiers cm de substrat entre deux arrosages",
    fertilizing: "Engrais liquide toutes les 4 semaines en saison",
    pruning: "Retirer les feuilles abîmées, tailler pour la forme",
    repotting: "Tous les 2 ans, pot légèrement plus grand",
    propagation: "Bouturage de tige, marcottage aérien",
    commonProblems: ["Taches brunes (excès d'eau)", "Chute de feuilles (changement brusque d'environnement)"],
    pests: ["Cochenilles", "Araignées rouges"],
    toxicity: "Toxique si ingéré",
    difficulty: "modere",
    petSafe: false,
    indoorOutdoor: "interieur",
    imageUrl: null,
  },
  {
    commonName: "Philodendron",
    scientificName: "Philodendron hederaceum",
    family: "Araceae",
    origin: "Amérique centrale",
    category: PlantCategory.tropicales,
    light: "Lumière indirecte, tolère la faible luminosité",
    temperatureRange: "18-27°C",
    humidity: "Moyenne à élevée",
    watering: "Laisser sécher légèrement en surface entre deux arrosages",
    fertilizing: "Engrais léger toutes les 4-6 semaines en saison",
    pruning: "Pincer les tiges pour densifier",
    repotting: "Tous les 2 ans, pot légèrement plus grand",
    propagation: "Bouturage de tige dans l'eau",
    commonProblems: ["Feuilles jaunes (excès d'eau)", "Étiolement (manque de lumière)"],
    pests: ["Cochenilles"],
    toxicity: "Toxique si ingéré",
    difficulty: "facile",
    petSafe: false,
    indoorOutdoor: "interieur",
    imageUrl: null,
  },
  {
    commonName: "Alocasia",
    scientificName: "Alocasia amazonica",
    family: "Araceae",
    origin: "Asie du Sud-Est",
    category: PlantCategory.tropicales,
    light: "Lumière vive et indirecte",
    temperatureRange: "18-27°C",
    humidity: "Élevée",
    watering: "Substrat légèrement humide, laisser sécher en surface entre deux",
    fertilizing: "Engrais dilué toutes les 4 semaines en saison",
    pruning: "Retirer les feuilles fanées à la base",
    repotting: "Tous les 2 ans, terreau aéré et drainant",
    propagation: "Division de rhizome",
    commonProblems: ["Bords secs (air trop sec)", "Pourriture du rhizome (excès d'eau)"],
    pests: ["Araignées rouges", "Cochenilles"],
    toxicity: "Toxique si ingéré",
    difficulty: "exigeant",
    petSafe: false,
    indoorOutdoor: "interieur",
    imageUrl: null,
  },
  {
    commonName: "Dieffenbachia",
    scientificName: "Dieffenbachia seguine",
    family: "Araceae",
    origin: "Amérique tropicale",
    category: PlantCategory.tropicales,
    light: "Lumière indirecte, tolère la mi-ombre",
    temperatureRange: "18-26°C",
    humidity: "Moyenne à élevée",
    watering: "Laisser sécher légèrement en surface entre deux arrosages",
    fertilizing: "Engrais léger toutes les 4-6 semaines en saison",
    pruning: "Retirer les feuilles jaunies à la base",
    repotting: "Tous les 2 ans, pot légèrement plus grand",
    propagation: "Bouturage de tige",
    commonProblems: ["Feuilles jaunes (excès d'eau)", "Tige dégarnie à la base (vieillissement naturel)"],
    pests: ["Cochenilles", "Araignées rouges"],
    toxicity: "Très toxique si ingéré (sève irritante)",
    difficulty: "facile",
    petSafe: false,
    indoorOutdoor: "interieur",
    imageUrl: null,
  },
  {
    commonName: "Oiseau de paradis",
    scientificName: "Strelitzia reginae",
    family: "Strelitziaceae",
    origin: "Afrique du Sud",
    category: PlantCategory.tropicales,
    light: "Lumière vive, quelques heures de soleil direct",
    temperatureRange: "16-26°C",
    humidity: "Moyenne",
    watering: "Laisser sécher légèrement entre deux arrosages",
    fertilizing: "Engrais pour plantes fleuries toutes les 4 semaines en saison",
    pruning: "Retirer les feuilles et fleurs fanées à la base",
    repotting: "Tous les 2-3 ans, pot profond",
    propagation: "Division de touffe",
    commonProblems: ["Absence de floraison (manque de lumière ou plant trop jeune)", "Feuilles fendues (normal, pas d'inquiétude)"],
    pests: ["Cochenilles", "Araignées rouges"],
    toxicity: "Légèrement toxique si ingéré",
    difficulty: "modere",
    petSafe: false,
    indoorOutdoor: "interieur",
    imageUrl: null,
  },
  {
    commonName: "Ciste",
    scientificName: "Cistus albidus",
    family: "Cistaceae",
    origin: "Bassin méditerranéen",
    category: PlantCategory.mediterraneennes,
    light: "Plein soleil",
    temperatureRange: "0-35°C",
    humidity: "Faible",
    watering: "Laisser sécher entre deux arrosages, très résistant à la sécheresse",
    fertilizing: "Peu exigeant, aucun engrais nécessaire en général",
    pruning: "Tailler légèrement après floraison",
    repotting: "Rarement, plante de pleine terre",
    propagation: "Semis, bouturage semi-ligneux",
    commonProblems: ["Pourriture des racines (excès d'eau)", "Peu de floraison (sol trop riche)"],
    pests: ["Peu de ravageurs connus"],
    toxicity: "Non toxique",
    difficulty: "facile",
    petSafe: true,
    indoorOutdoor: "exterieur",
    imageUrl: null,
  },
  {
    commonName: "Santoline",
    scientificName: "Santolina chamaecyparissus",
    family: "Asteraceae",
    origin: "Bassin méditerranéen",
    category: PlantCategory.mediterraneennes,
    light: "Plein soleil",
    temperatureRange: "0-35°C",
    humidity: "Faible",
    watering: "Laisser sécher entre deux arrosages, résiste très bien à la sécheresse",
    fertilizing: "Peu exigeante, engrais léger au printemps suffit",
    pruning: "Tailler après floraison pour garder une forme compacte",
    repotting: "Tous les 2-3 ans, terreau très drainant",
    propagation: "Bouturage semi-ligneux",
    commonProblems: ["Pourriture (excès d'eau)", "Touffe qui se dégarnit (manque de taille)"],
    pests: ["Peu de ravageurs connus"],
    toxicity: "Non toxique",
    difficulty: "facile",
    petSafe: true,
    indoorOutdoor: "exterieur",
    imageUrl: null,
  },
  {
    commonName: "Pétunia",
    scientificName: "Petunia × hybrida",
    family: "Solanaceae",
    origin: "Amérique du Sud",
    category: PlantCategory.jardin,
    light: "Plein soleil",
    temperatureRange: "10-28°C",
    humidity: "Moyenne",
    watering: "Arrosage régulier, ne pas laisser sécher complètement en été",
    fertilizing: "Engrais pour plantes fleuries toutes les 2 semaines en saison",
    pruning: "Retirer les fleurs fanées pour prolonger la floraison",
    repotting: "Culture souvent annuelle",
    propagation: "Semis, bouturage de tige",
    commonProblems: ["Peu de fleurs (manque de lumière)", "Tiges qui s'allongent trop (manque de pincement)"],
    pests: ["Pucerons", "Chenilles"],
    toxicity: "Non toxique",
    difficulty: "facile",
    petSafe: false,
    indoorOutdoor: "les-deux",
    imageUrl: null,
  },
  {
    commonName: "Zinnia",
    scientificName: "Zinnia elegans",
    family: "Asteraceae",
    origin: "Mexique",
    category: PlantCategory.jardin,
    light: "Plein soleil",
    temperatureRange: "15-30°C",
    humidity: "Moyenne",
    watering: "Arrosage régulier au pied, éviter de mouiller le feuillage",
    fertilizing: "Engrais pour plantes fleuries toutes les 3 semaines en saison",
    pruning: "Retirer les fleurs fanées pour prolonger la floraison",
    repotting: "Culture annuelle, semis chaque année",
    propagation: "Semis",
    commonProblems: ["Oïdium (air confiné et humide)", "Tiges faibles (manque de soleil)"],
    pests: ["Pucerons", "Limaces"],
    toxicity: "Non toxique",
    difficulty: "facile",
    petSafe: true,
    indoorOutdoor: "exterieur",
    imageUrl: null,
  },
  {
    commonName: "Narcisse",
    scientificName: "Narcissus spp.",
    family: "Amaryllidaceae",
    origin: "Europe, Asie",
    category: PlantCategory.bulbes,
    light: "Plein soleil à mi-ombre",
    temperatureRange: "0-20°C",
    humidity: "Moyenne",
    watering: "Arrosage modéré, éviter l'eau stagnante autour du bulbe",
    fertilizing: "Engrais pour bulbes à la plantation",
    pruning: "Laisser le feuillage jaunir naturellement après floraison",
    repotting: "Replantation tous les 3-4 ans",
    propagation: "Division des bulbilles",
    commonProblems: ["Pourriture du bulbe (excès d'eau)", "Absence de floraison (division nécessaire)"],
    pests: ["Mouche du narcisse"],
    toxicity: "Très toxique si ingéré",
    difficulty: "facile",
    petSafe: false,
    indoorOutdoor: "les-deux",
    imageUrl: null,
  },
  {
    commonName: "Crocus",
    scientificName: "Crocus vernus",
    family: "Iridaceae",
    origin: "Europe, Asie",
    category: PlantCategory.bulbes,
    light: "Plein soleil à mi-ombre",
    temperatureRange: "5-18°C",
    humidity: "Moyenne",
    watering: "Arrosage modéré, laisser sécher légèrement entre deux",
    fertilizing: "Peu exigeant, engrais léger à la plantation",
    pruning: "Laisser le feuillage jaunir naturellement",
    repotting: "Replantation tous les 3-4 ans",
    propagation: "Division des cormes",
    commonProblems: ["Pourriture du corme (excès d'eau)", "Rongeurs (extérieur)"],
    pests: ["Pucerons"],
    toxicity: "Légèrement toxique si ingéré",
    difficulty: "facile",
    petSafe: false,
    indoorOutdoor: "exterieur",
    imageUrl: null,
  },
  {
    commonName: "Fougère nid d'oiseau",
    scientificName: "Asplenium nidus",
    family: "Aspleniaceae",
    origin: "Régions tropicales",
    category: PlantCategory.fougeres,
    light: "Lumière indirecte, ambiance humide",
    temperatureRange: "18-26°C",
    humidity: "Élevée",
    watering: "Substrat toujours légèrement humide, ne jamais détremper le cœur",
    fertilizing: "Engrais très dilué toutes les 4-6 semaines",
    pruning: "Retirer les frondes sèches à la base",
    repotting: "Tous les 2 ans, terreau léger",
    propagation: "Spores (lent), division rare",
    commonProblems: ["Frondes brunes (air trop sec)", "Pourriture du cœur (eau stagnante au centre)"],
    pests: ["Cochenilles"],
    toxicity: "Non toxique",
    difficulty: "modere",
    petSafe: true,
    indoorOutdoor: "interieur",
    imageUrl: null,
  },
  {
    commonName: "Rossolis",
    scientificName: "Drosera capensis",
    family: "Droseraceae",
    origin: "Afrique du Sud",
    category: PlantCategory.carnivores,
    light: "Lumière très vive",
    temperatureRange: "10-30°C",
    humidity: "Élevée",
    watering: "Substrat toujours humide, uniquement eau de pluie ou déminéralisée",
    fertilizing: "Aucun engrais — se nourrit d'insectes",
    pruning: "Retirer les feuilles fanées",
    repotting: "Chaque année, substrat tourbe/sable sans calcaire",
    propagation: "Semis, feuilles bouturées",
    commonProblems: ["Faible production de rosée (manque de lumière)", "Affaiblissement (eau calcaire)"],
    pests: ["Peu de ravageurs connus"],
    toxicity: "Non toxique",
    difficulty: "modere",
    petSafe: true,
    indoorOutdoor: "interieur",
    imageUrl: null,
  },
  {
    commonName: "Papyrus",
    scientificName: "Cyperus papyrus",
    family: "Cyperaceae",
    origin: "Afrique",
    category: PlantCategory.aquatiques,
    light: "Plein soleil à mi-ombre",
    temperatureRange: "15-30°C",
    humidity: "Aquatique",
    watering: "Base toujours immergée ou substrat détrempé en permanence",
    fertilizing: "Engrais aquatique en tablettes en saison",
    pruning: "Retirer les tiges sèches à la base",
    repotting: "Tous les 2 ans, division de touffe",
    propagation: "Division de touffe, bouturage d'ombelle",
    commonProblems: ["Jaunissement (eau trop froide)", "Croissance faible (manque de lumière)"],
    pests: ["Pucerons"],
    toxicity: "Non toxique",
    difficulty: "modere",
    petSafe: true,
    indoorOutdoor: "exterieur",
    imageUrl: null,
  },
  {
    commonName: "Pin bonsaï",
    scientificName: "Pinus thunbergii",
    family: "Pinaceae",
    origin: "Japon",
    category: PlantCategory.bonsais,
    light: "Plein soleil, extérieur toute l'année",
    temperatureRange: "-15 à 30°C",
    humidity: "Moyenne",
    watering: "Laisser sécher légèrement entre deux arrosages",
    fertilizing: "Engrais pour bonsaïs au printemps et en été",
    pruning: "Pincer les nouvelles pousses (candles) au printemps",
    repotting: "Tous les 2-3 ans, terreau spécial bonsaï pin",
    propagation: "Semis, greffe",
    commonProblems: ["Jaunissement des aiguilles (excès d'eau)", "Faible ramification (manque de pincement)"],
    pests: ["Cochenilles"],
    toxicity: "Non toxique",
    difficulty: "exigeant",
    petSafe: true,
    indoorOutdoor: "exterieur",
    imageUrl: null,
  },
  {
    commonName: "Genévrier bonsaï",
    scientificName: "Juniperus chinensis",
    family: "Cupressaceae",
    origin: "Asie de l'Est",
    category: PlantCategory.bonsais,
    light: "Plein soleil, extérieur toute l'année",
    temperatureRange: "-15 à 30°C",
    humidity: "Moyenne",
    watering: "Laisser sécher légèrement le dessus du substrat entre deux arrosages",
    fertilizing: "Engrais pour bonsaïs au printemps et en été",
    pruning: "Pincer régulièrement pour maintenir la forme",
    repotting: "Tous les 2-3 ans, terreau spécial bonsaï",
    propagation: "Bouturage, greffe",
    commonProblems: ["Brunissement (excès d'eau ou manque de lumière)", "Faible densité (manque de pincement)"],
    pests: ["Araignées rouges"],
    toxicity: "Légèrement toxique si ingéré",
    difficulty: "modere",
    petSafe: false,
    indoorOutdoor: "exterieur",
    imageUrl: null,
  },
];

async function main() {
  console.log("🌱 Seed — Le Jardin de Bloom (données de démonstration)");

  await prisma.userAchievement.deleteMany({});
  await prisma.achievement.deleteMany({});
  for (const achievement of ACHIEVEMENTS) {
    await prisma.achievement.create({ data: achievement });
  }
  console.log(`  ✔ ${ACHIEVEMENTS.length} badges créés`);

  const speciesRecords = [];
  for (const species of SPECIES) {
    const record = await prisma.plantSpecies.upsert({
      where: { scientificName: species.scientificName as string },
      update: species,
      create: species,
    });
    speciesRecords.push(record);
  }
  console.log(`  ✔ ${speciesRecords.length} espèces créées`);

  const existingDemo = await prisma.user.findUnique({ where: { email: "demo@jardindebloom.app" } });
  if (existingDemo) {
    await prisma.user.delete({ where: { id: existingDemo.id } });
  }

  const passwordHash = await bcrypt.hash("JardinDeBloom2026!", 10);
  const demoUser = await prisma.user.create({
    data: {
      email: "demo@jardindebloom.app",
      passwordHash,
      name: "Demo",
      city: "Lyon",
      plantLocationType: "interieur",
      pets: ["chat"],
      plantCountRange: "1-5",
      onboardedAt: new Date(),
      consentLocation: true,
      consentNotifications: true,
      virtualGarden: {
        create: { season: "autumn", level: 2 },
      },
    },
    include: { virtualGarden: true },
  });
  console.log(`  ✔ Utilisateur démo créé (${demoUser.email})`);

  await prisma.weatherSnapshot.create({
    data: {
      city: "Lyon",
      temperatureC: 18,
      humidityPct: 55,
      rainProbability: 0.3,
      rainAmountMm: 1.2,
      windSpeedKmh: 10,
      condition: "partly_cloudy",
    },
  });

  const plantSeeds = [
    {
      species: speciesRecords[0]!,
      name: "Mon Monstera",
      status: "healthy" as const,
      healthScores: [68, 74, 79, 84],
      location: { name: "Salon", room: "Salon", indoorOutdoor: "interieur", windowOrientation: "sud-est", distanceToWindowM: 1.2 },
      environment: { name: "Salon lumineux", temperatureC: 21, humidityPct: 50, lightDescription: "Lumière vive filtrée toute la journée" },
    },
    {
      species: speciesRecords[1]!,
      name: "Mon Calathea",
      status: "watch" as const,
      healthScores: [80, 76, 70, 66],
      location: { name: "Chambre", room: "Chambre", indoorOutdoor: "interieur", windowOrientation: "nord", distanceToWindowM: 2.0 },
      environment: { name: "Chambre douce", temperatureC: 19, humidityPct: 40, lightDescription: "Lumière indirecte modérée" },
    },
    {
      species: speciesRecords[2]!,
      name: "Mon Basilic",
      status: "healthy" as const,
      healthScores: [72, 80, 88],
      location: { name: "Cuisine", room: "Cuisine", indoorOutdoor: "interieur", windowOrientation: "sud", distanceToWindowM: 0.3 },
      environment: { name: "Rebord de fenêtre", temperatureC: 22, humidityPct: 45, lightDescription: "Plein soleil une partie de la journée" },
    },
    {
      species: speciesRecords[3]!,
      name: "Mon Citronnier",
      status: "attention" as const,
      healthScores: [90, 82, 71, 58],
      location: { name: "Balcon", room: "Balcon", indoorOutdoor: "exterieur", windowOrientation: "sud-ouest", distanceToWindowM: 0 },
      environment: { name: "Balcon exposé", temperatureC: 14, humidityPct: 60, lightDescription: "Plein soleil, exposé au vent" },
    },
  ];

  let totalPhotos = 0;
  let totalCareActions = 0;

  for (const seed of plantSeeds) {
    const location = await prisma.plantLocation.create({ data: seed.location });
    const environment = await prisma.environment.create({ data: seed.environment });

    const plant = await prisma.plant.create({
      data: {
        userId: demoUser.id,
        speciesId: seed.species.id,
        name: seed.name,
        status: seed.status,
        healthScore: seed.healthScores[seed.healthScores.length - 1],
        locationId: location.id,
        environmentId: environment.id,
        notes: null,
      },
    });

    const photoBase = (seed.species.imageUrl as string) ?? "/plants/placeholder-monstera.svg";
    const photos = [];
    for (let i = 0; i < seed.healthScores.length; i++) {
      const photo = await prisma.plantPhoto.create({
        data: {
          plantId: plant.id,
          storageKey: `demo:${photoBase}`,
          caption: `Photo ${i + 1}`,
          takenAt: new Date(Date.now() - (seed.healthScores.length - i) * 7 * 24 * 60 * 60 * 1000),
        },
      });
      photos.push(photo);
      totalPhotos++;
    }

    for (let i = 0; i < seed.healthScores.length; i++) {
      const score = seed.healthScores[i]!;
      await prisma.healthAnalysis.create({
        data: {
          plantId: plant.id,
          photoId: photos[i]!.id,
          score,
          confidence: 0.7 + i * 0.05,
          observations: {
            yellowLeaves: seed.status === "attention" && i === seed.healthScores.length - 1,
            brownLeaves: false,
            wilting: false,
            spots: seed.status === "watch" && i >= seed.healthScores.length - 2,
            pestsVisible: false,
          },
          hypotheses: seed.status !== "healthy" ? ["Arrosage à ajuster", "Luminosité à vérifier"] : [],
          recommendations: seed.status !== "healthy" ? ["Vérifier le substrat avant d'arroser", "Observer l'évolution sur 7 jours"] : ["Continuer le suivi habituel"],
          createdAt: new Date(Date.now() - (seed.healthScores.length - i) * 7 * 24 * 60 * 60 * 1000),
        },
      });
    }

    const careAction = await prisma.careAction.create({
      data: {
        plantId: plant.id,
        type: CareActionType.watering,
        note: "Arrosage régulier",
        performedAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000),
      },
    });
    await prisma.wateringEvent.create({
      data: { careActionId: careAction.id, amountMl: 200, substrateWasDry: true },
    });
    totalCareActions++;

    const fertilizeAction = await prisma.careAction.create({
      data: {
        plantId: plant.id,
        type: CareActionType.fertilizing,
        note: "Engrais liquide dilué",
        performedAt: new Date(Date.now() - 14 * 24 * 60 * 60 * 1000),
      },
    });
    await prisma.fertilizingEvent.create({
      data: { careActionId: fertilizeAction.id, product: "Engrais plantes vertes", dilution: "1/2 dose" },
    });
    totalCareActions++;

    if (seed.status !== "healthy") {
      await prisma.reminder.create({
        data: {
          userId: demoUser.id,
          plantId: plant.id,
          type: seed.status === "attention" ? ReminderType.check_substrate : ReminderType.observe,
          message:
            seed.status === "attention"
              ? `🌿 ${seed.name} pourrait avoir besoin d'un petit coup d'œil. Peux-tu vérifier le substrat ?`
              : `📸 Observe ${seed.name} de près, Bloom a repéré un petit détail.`,
          scheduledFor: new Date(Date.now() + 24 * 60 * 60 * 1000),
        },
      });
    }

    await prisma.gardenItem.create({
      data: {
        virtualGardenId: demoUser.virtualGarden!.id,
        plantId: plant.id,
        type: seed.status === "healthy" ? "tree" : "sprout",
        growthStage: seed.status === "healthy" ? 3 : 1,
        originAction: "plant_added",
      },
    });
  }

  console.log(`  ✔ ${plantSeeds.length} plantes créées (${totalPhotos} photos, ${totalCareActions} soins)`);

  const unlockedIds = ["first_plant", "first_scan", "first_analysis", "first_care", "first_bloom_meeting", "first_garden", "collection_3", "care_10", "photos_10", "first_discovery", "first_garden_item", "first_tree"];
  for (const id of unlockedIds) {
    await prisma.userAchievement.create({
      data: { userId: demoUser.id, achievementId: id },
    });
  }
  console.log(`  ✔ ${unlockedIds.length} badges débloqués pour la démo`);

  console.log("🌸 Seed terminé — connecte-toi avec demo@jardindebloom.app / JardinDeBloom2026!");
}

main()
  .catch((error) => {
    console.error(error);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
